spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: {{LOCALHOST_MYSQL_URI}}
    username: {{LOCAHOST_MYSQL_USERNAME}}
    password: {{LOCAHOST_MYSQL_PASSWORD}}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
