server:
  port: 8080

spring:
  datasource:
    platform: mysql
    dbcp2.driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://34.88.134.140:3306/grindhouse'
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      generate-ddl: true
  redis:
    host: localhost
    port: 3679
