server:
  port: 8081

spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: Grootpan199!
    url: jdbc:mysql://localhost:3306/grindhouse?createDatabaseIfNotExist=true
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  redis:
    host: localhost
    port: 3679

